name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Download Gradle
        run: java -version && wget -q https://services.gradle.org/distributions/gradle-6.0.1-bin.zip && unzip gradle-6.0.1-bin.zip && ls -lkah